feat(loopback4-dynamic-datasource): package update
sourcefuse/loopback4-dynamic-datasource pull request #4
Opened 2024-02-05 05:12 UTC by karuneshsf

Updated loopback and other packages

GH-1

2024-02-05 05:32 UTC, yeshamavani requested changes

2024-02-05 05:32 UTC, yeshamavani commented on package.json
change the node support version
>=18

2024-02-05 05:32 UTC, yeshamavani commented on package.json
'>=18'

2024-02-07 12:30 UTC, dev-hitesh-gupta approved these changes

2024-02-08 07:58 UTC, merged